### ISSUE TITLE
build failed on latest Xcode

### ISSUE THREAD

**Issue by kmddd59** [tihmstar/futurerestore#22]
![screen shot 2017-01-03 at 6 58 06 pm](https://cloud.githubusercontent.com/assets/5413229/21630507/a1f6be76-d1e6-11e6-8d52-c7653a74c051.png)
I'm no expert but i don't think the red ones are good

**Comment by Packetfahrer** [comment]
you can't do this with Xcode. Better you download it. 

http://api.tihmstar.net/builds/futurerestore/futurerestore-latest.zip

**Comment by CyberiumShadow** [comment]
@kmddd59 you're supposed to do `bash autogen.sh && make`

**Comment by kmddd59** [comment]
you could of warned every one lol

**Comment by joie1** [comment]
Hello, i wish to have this futurerestore's new build before ios 10.2.1 close, for restoring my ipad to ios 10.2, because i have this issue when i try to restore, "About to restore device... 
Waiting for device...
ERROR: Unable to connect to device in restore mode
ERROR: Unable to open device in restore mode
[Error] ERROR: Unable to restore device
Done: restoring failed.
Failed with errorcode=-11"

So i tried to compile futurerestore with my mac, with terminal, and i had this issue, this is the full text of my terminal, apears that i had to have libimobiledevice 1.2.1, but don't now who? any inspiration?

"Pc-de-jo-intel-i7:futurerestore job$ sudo /Users/job/Documents/futurerestore/autogen.sh 
glibtoolize: putting auxiliary files in '.'.
glibtoolize: linking file './ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: linking file 'm4/libtool.m4'
glibtoolize: linking file 'm4/ltoptions.m4'
glibtoolize: linking file 'm4/ltsugar.m4'
glibtoolize: linking file 'm4/ltversion.m4'
glibtoolize: linking file 'm4/lt~obsolete.m4'
configure.ac:37: installing './compile'
configure.ac:15: installing './missing'
futurerestore/Makefile.am: installing './depcomp'
~/Documents/futurerestore/external/idevicerestore ~/Documents/futurerestore
/Users/job/Documents/futurerestore/autogen.sh: line 18: ./autogen.sh: No such file or directory
~/Documents/futurerestore
~/Documents/futurerestore/external/img4tool ~/Documents/futurerestore
/Users/job/Documents/futurerestore/autogen.sh: line 18: ./autogen.sh: No such file or directory
~/Documents/futurerestore
~/Documents/futurerestore/external/tsschecker ~/Documents/futurerestore
/Users/job/Documents/futurerestore/autogen.sh: line 18: ./autogen.sh: No such file or directory
~/Documents/futurerestore
checking build system type... x86_64-apple-darwin16.4.0
checking host system type... x86_64-apple-darwin16.4.0
checking target system type... x86_64-apple-darwin16.4.0
checking whether we need platform-specific build settings... checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libplist... yes
checking for libzip... yes
checking for libimobiledevice... no
configure: error: Package requirements (libimobiledevice-1.0 >= 1.2.1) were not met:

Requested 'libimobiledevice-1.0 >= 1.2.1' but version of libimobiledevice is 1.2.0

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libimobiledevice_CFLAGS
and libimobiledevice_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details."
