### ISSUE TITLE
Dont know how to install it on Windows

### ISSUE THREAD

**Issue by 995qa** [tihmstar/futurerestore#324]
Can u help me install this on windows

**Comment by Darthagnon** [comment]
Installation is not needed; put it somewhere and run it from the command line. You can optionally add the EXE to your PATH. 

Problem is, you need an EXE first. I don't know how to build it. Would be nice if one of the original devs could do a binary build, since they've got the development environments and dependencies all set up already. 

Currently, your next best bet is to use the Windows binary build by s0uthwest, though it's not fully up-to-date: https://github.com/s0uthwest/futurerestore/releases

NB if you don't know how to "install" it on Windows, then maybe you shouldn't use it? It's powerful software that can brick your devices.

**Comment by ZackeryCole** [comment]
Ok i understand

**Comment by masckmaster2007** [comment]
You should close it ?
