### ISSUE TITLE
Abort trap 6: malloc: *** error for object 0x7f82fad00a50: pointer being freed was not allocated

### ISSUE THREAD

**Issue by BlackGeekTutorial** [tihmstar/futurerestore#5]
Had this error from the latest futurerestore build (compiled on my own from this GitHub source)

MBP-di-Andrea:Downgrade benti$ futurerestore  -t 4868990219897894_iPhone8,1_10.1.1-14B150.shsh -b Mav13-2.41.00.Release.bbfw -p BuildManifest.plist —s sep-firmware.n71m.RELEASE.im4p -m BuildManifest.plist -w iPhone_4.7_10.1.1_14B150_Restore.ipsw
Found device in Recovery mode
Device already in Recovery mode
INFO: device serial number is (DELETED)
waiting for nonce: dc 87 f6 4b 77 39 fd df 4f 9f 32 d3 d5 07 df ed a1 7f 8e 9c
Got ApNonce from device: dc 87 f6 4b 77 39 fd df 4f 9f 32 d3 d5 07 df ed a1 7f 8e 9c
Device has requested ApNonce now
done
futurerestore(13989,0x7fffdd2953c0) malloc: *** error for object 0x7f82fad00a50: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

**Comment by leo98gomez** [comment]
I'm getting similar error (iPhone6s+ iOS 9.3.3 N66AP)
<img width="850" alt="prometheus error" src="https://cloud.githubusercontent.com/assets/15682607/21558741/8e78cd16-ce04-11e6-973f-47693c714f98.png">

**Comment by matteyeux** [comment]
@BlackGeekTutorial what if you run ideviceinfo ? I had the same issue for all Libimobiledevice bins

**Comment by BlackGeekTutorial** [comment]
@matteyeux Yup it gives the same error. Did you fix it?

**Comment by tihmstar** [comment]
So this seems to be related to libimobiledevice then?
Have you tried updating thoese libs?

**Comment by BlackGeekTutorial** [comment]
@tihmstar Yes, compiled and installed latest build form the official source under macOS Sierra

**Comment by BlackGeekTutorial** [comment]
@tihmstar This is what Xcode says:
<img width="1512" alt="schermata 2016-01-01 alle 20 57 16" src="https://cloud.githubusercontent.com/assets/5960656/21582748/fe26ee60-d064-11e6-9daf-3575f1700ff3.png">

**Comment by CyberiumShadow** [comment]
Yeah I've gotten that error as well with my self-compiled version

**Comment by tihmstar** [comment]
Is the issue still in the latest version? (b35d3e1245da49950028d753b1bdb40fce5d21d5)

**Comment by ryu16** [comment]
I encountered similar problem.

$ ./futurerestore
Version: b35d3e1245da49950028d753b1bdb40fce5d21d5 - 90
Usage: futurerestore [OPTIONS] IPSW
Allows restoring nonmatching iOS/Sep/Baseband

  -t, --apticket PATH		Apticket used for restoring
  -b, --baseband PATH		Baseband to be flashed
  -p, --baseband-manifest PATH	Buildmanifest for requesting baseband ticket
  -s, --sep PATH		Sep to be flashed
  -m, --sep-manifest PATH	Buildmanifest for requesting sep ticket
  -w, --wait			keep rebooting until nonce matches APTicket
  -u, --update			update instead of erase install
      --latest-sep		use latest signed sep instead of manually specifying one(may cause bad restore)
      --latest-baseband		se latest signed baseband instead of manually specifying one(may cause bad restore)
      --no-baseband		skip checks and don't flash baseband.
                   		WARNING: only use this for device without baseband (eg iPod or some wifi only iPads)

futurerestore(31618,0x7fffba0d53c0) malloc: *** error for object 0x7fc72f504ad0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

$ otool -L futurerestore
futurerestore:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
	/usr/local/opt/libzip/lib/libzip.4.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/local/lib/libimobiledevice.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/local/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/local/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/local/opt/usbmuxd/lib/libusbmuxd.4.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/local/opt/libplist/lib/libplist.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/local/lib/libfragmentzip.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 8.0.0)
	/usr/local/lib/libirecovery.2.dylib (compatibility version 3.0.0, current version 3.1.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1348.1.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)

**Comment by kurdok** [comment]
sorry guys but could you please suggest or advise any solution for this:
$ ./futurerestore_macos 
Version: 481d959a5e36f22aa0b2bcb58914ab84b8107f4d - 94
Usage: futurerestore [OPTIONS] IPSW
Allows restoring nonmatching iOS/Sep/Baseband

  -t, --apticket PATH		Apticket used for restoring
  -b, --baseband PATH		Baseband to be flashed
  -p, --baseband-manifest PATH	Buildmanifest for requesting baseband ticket
  -s, --sep PATH		Sep to be flashed
  -m, --sep-manifest PATH	Buildmanifest for requesting sep ticket
  -w, --wait			keep rebooting until nonce matches APTicket
  -u, --update			update instead of erase install
      --latest-sep		use latest signed sep instead of manually specifying one(may cause bad restore)
      --latest-baseband		se latest signed baseband instead of manually specifying one(may cause bad restore)
      --no-baseband		skip checks and don't flash baseband.
                   		WARNING: only use this for device without baseband (eg iPod or some wifi only iPads)

futurerestore_macos(39468,0x7fff9b6693c0) malloc: *** error for object 0x7fa25940e2d0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

**Comment by tihmstar** [comment]
This might be related to https://github.com/libimobiledevice/libimobiledevice/issues/383
Looks like you're linking against the wrong version of openssl.
i also had similar issues when linking against 1.1.0 and resolved them by linking against 1.0.1
