### ISSUE TITLE
plz help me 

### ISSUE THREAD

**Issue by elouardi99** [tihmstar/futurerestore#58]
Waiting for device…
ERROR: Unable to connect to device in restore mode
ERROR: Unable to open device in restore mode
[Error] ERROR: Unable to restore device
Done: restoring failed.
Failed with errorcode=-11

**Comment by adrianmkofficial** [comment]
Suggestion: To shed more light on your issue, perhaps edit your post with most of this **Log**, not just the last few lines, since this error appears to be caused by different problems (wild guessing here)...

**Comment by gkeyes** [comment]
the same for me.

**Comment by Pollsmor** [comment]
You have to add your iPhone as a USB device filter. However, remove everything in the columns except for the "Name" (fill in Apple Inc. iPhone) and "Manufacturer", which should stay as Apple Inc. All the others should be blank.

This is because for some reason the device ID or whatever changes after every restore.
