### ISSUE TITLE
Error 11: restore_is_current_device: *** is not in restore mode

### ISSUE THREAD

**Issue by brymonster** [tihmstar/futurerestore#77]
iPad Air 9.0.2 cl0ver patched. nonce set using nvpatch
macOS. 
tried multiple times. 
blobs are good. 
>./futurerestore_macos -t 2081521660945458_iPad4,1_j71ap_10.2-14C92.shsh2 -s sep-firmware.j71.RELEASE.im4p -m BuildManifest.plist -w iPad_64bit_10.2_14C92_Restore.ipsw --no-baseband
Version: b35d3e1245da49950028d753b1bdb40fce5d21d5 - 90
futurerestore init done
reading ticket 2081521660945458_iPad4,1_j71ap_10.2-14C92.shsh2 done
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbChipID node
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received

WARNING: user specified not to flash a baseband. This can make the restore fail if the device needs a baseband!
if you added this flag by mistake you can press CTRL-C now to cancel
continuing restore in 5 4 3 2 1 
Found device in Recovery mode
Device already in Recovery mode
INFO: device serial number is DMPM6P6RFK11
waiting for nonce: 56 33 79 b5 27 5c fd 07 66 76 93 f5 ff d6 2b 52 d9 27 2f 66 
Got ApNonce from device: 56 33 79 b5 27 5c fd 07 66 76 93 f5 ff d6 2b 52 d9 27 2f 66 
Device has requested ApNonce now
Found device in Recovery mode
Identified device as j71ap, iPad4,1
Extracting BuildManifest from IPSW
Product Version: 10.2
Product Build: 14C92 Major: 14
Device supports Image4: true
checking APTicket to be valid for this restore...
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Using cached filesystem from 'iPad_64bit_10.2_14C92_Restore/058-54456-094.dmg'
Extracting iBEC.j71.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (644248 bytes)...
waiting for device to reconnect... 
Getting SepNonce in recovery mode... 64 fe 01 1f 25 f6 fa 57 9d 0e 77 dc dc ce 15 40 5b 45 46 f2 
Getting ApNonce in recovery mode... 56 33 79 b5 27 5c fd 07 66 76 93 f5 ff d6 2b 52 d9 27 2f 66 
Recovery Mode Environment:
iBoot build-version=iBoot-2817.1.94
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@2x~ipad.s5l8960x.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (22710 bytes)...
ramdisk-size=0x10000000
Extracting 058-54560-094.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (40342551 bytes)...
Extracting DeviceTree.j71ap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (101101 bytes)...
Extracting kernelcache.release.j71...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (12032443 bytes)...
Trying to fetch new SHSH blob
WARNING: Unable to find BbChipID node
WARNING: Unable to find BbSkeyId node
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device... 
Waiting for device...
restore_is_current_device: device 075941b2bdaf70aa731d42b1e5e2f1121167c29a is not in restore mode
ERROR: Unable to connect to device in restore mode
ERROR: Unable to open device in restore mode
[Error] ERROR: Unable to restore device
Done: restoring failed.
Failed with errorcode=-11

**Comment by brymonster** [comment]
[same.txt](https://github.com/tihmstar/futurerestore/files/826545/same.txt)

**Comment by brymonster** [comment]
i see that this issue has been handled in https://github.com/tihmstar/futurerestore/issues/33
but in my limited skill i _can not_ figure out how to use the branch: https://github.com/tihmstar/futurerestore/tree/b35d3e1245da49950028d753b1bdb40fce5d21d5
do i need a compiled version to restore with?

**Comment by brymonster** [comment]
Has anyone had success in getting around error 11?  im on macOS. not VM. 
my ipad is not rebooting. not flashing green..
i am so close. :(

[newest ERROR11.txt](https://github.com/tihmstar/futurerestore/files/853856/newest.ERROR11.txt)

**Comment by tihmstar** [comment]
Can you check whether the problem still exists in version 95?
Attempting to fix this in 9fcf613f8fe68b15be7fd19c267e7351523eb387

**Comment by TChenGH** [comment]
@tihmstar look this
[错误95.txt](https://github.com/tihmstar/futurerestore/files/871874/95.txt)and this
![2017-03-27 4 44 02](https://cloud.githubusercontent.com/assets/26371152/24348252/a2576650-130d-11e7-9a36-787f9939a0c5.png)


Last login: Mon Mar 27 16:17:11 on ttys001
TChendeMac:~ tchen$ cd ~/Desktop/downgrade
TChendeMac:downgrade tchen$ chmod +x futurerestore_macos
TChendeMac:downgrade tchen$ ./futurerestore_macos
Version: 9fcf613f8fe68b15be7fd19c267e7351523eb387 - 95
Usage: futurerestore [OPTIONS] IPSW
Allows restoring nonmatching iOS/Sep/Baseband

  -t, --apticket PATH		Apticket used for restoring
  -b, --baseband PATH		Baseband to be flashed
  -p, --baseband-manifest PATH	Buildmanifest for requesting baseband ticket
  -s, --sep PATH		Sep to be flashed
  -m, --sep-manifest PATH	Buildmanifest for requesting sep ticket
  -w, --wait			keep rebooting until nonce matches APTicket
  -u, --update			update instead of erase install
      --latest-sep		use latest signed sep instead of manually specifying one(may cause bad restore)
      --latest-baseband		se latest signed baseband instead of manually specifying one(may cause bad restore)
      --no-baseband		skip checks and don't flash baseband.
                   		WARNING: only use this for device without baseband (eg iPod or some wifi only iPads)

TChendeMac:downgrade tchen$ ./futurerestore_macos -t 16301120476826_iPhone7,2_10.2-14C92.shsh2 -b Mav10-5.32.00.Release.bbfw -p BuildManifest.plist  -s sep-firmware.n61.RELEASE.im4p -m BuildManifest.plist -w iPhone_4.7_10.2_14C92_Restore.ipsw
Version: 9fcf613f8fe68b15be7fd19c267e7351523eb387 - 95
futurerestore init done
reading ticket 16301120476826_iPhone7,2_10.2-14C92.shsh2 done
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is DNPP4GPZG5MN
waiting for nonce: 9f 79 d9 b3 95 98 4a 8e 65 05 31 8c 8e 02 48 15 52 90 11 fa 
Got ApNonce from device: 9f 79 d9 b3 95 98 4a 8e 65 05 31 8c 8e 02 48 15 52 90 11 fa 
Device has requested ApNonce now
Found device in Recovery mode
Identified device as n61ap, iPhone7,2
Extracting BuildManifest from IPSW
Product Version: 10.2
Product Build: 14C92 Major: 14
Device supports Image4: true
checking APTicket to be valid for this restore...
[Error] ECID inside APTicket does not match device ECID
APTicket is valid for      ed3667ed69a but device is   16301120476826
[Error] APTicket can't be used for restoring this device
Done: restoring failed.
Failed with errorcode=-45
TChendeMac:downgrade tchen$

**Comment by GeekBreak** [comment]
FutureRestore says that blobs aren't valid but I saved mine specifying my ECID, grabbed from UDID Calculator from Cydia, and img4tool says that are valid...so doesn't make sense.

img4tool Output: https://ghostbin.com/paste/5uqfy

futurerestore Output:
geekbreak@geekbreak-pc:~/Scrivania/downgrade/futurerestore/futurerestore$ sudo ./futurerestore -t '/home/geekbreak/Scrivania/downgrade/7068681191452461062_iPhone8,1_n71map_10.2-14C92.shsh2' -b '/home/geekbreak/Scrivania/downgrade/Mav13-2.41.00.Release.bbfw' -p '/home/geekbreak/Scrivania/downgrade/BuildManifest.plist' -s '/home/geekbreak/Scrivania/downgrade/sep-firmware.n71m.RELEASE.im4p' -m '/home/geekbreak/Scrivania/downgrade/BuildManifest.plist' -w '/home/geekbreak/Scrivania/downgrade/iPhone_4.7_10.2_14C92_Restore.ipsw'
Version: 9fcf613f8fe68b15be7fd19c267e7351523eb387 - 95
futurerestore init done
reading ticket /home/geekbreak/Scrivania/downgrade/7068681191452461062_iPhone8,1_n71map_10.2-14C92.shsh2 done
[TSSC] opening /home/geekbreak/Scrivania/downgrade/BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[TSSC] opening /home/geekbreak/Scrivania/downgrade/BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is FK6QLLPEGRY9
waiting for nonce: 82 2a 2d 1e db 51 de 15 a1 30 69 a1 0d 4d 7e b8 93 d4 ce e2 
Got ApNonce from device: 82 2a 2d 1e db 51 de 15 a1 30 69 a1 0d 4d 7e b8 93 d4 ce e2 
Device has requested ApNonce now
Found device in Recovery mode
Identified device as n71map, iPhone8,1
Extracting BuildManifest from IPSW
Product Version: 10.2
Product Build: 14C92 Major: 14
Device supports Image4: true
checking APTicket to be valid for this restore...
[Error] ECID inside APTicket does not match device ECID
APTicket is valid for 6219001797024806 but device is   16182630f81c26
[Error] APTicket can't be used for restoring this device
Done: restoring failed.
Failed with errorcode=-45
geekbreak@geekbreak-pc:~/Scrivania/downgrade/futurerestore/futurerestore$

**Comment by GeekBreak** [comment]
So...apparently that's my fault, I didn't read with attention the warning on rJailbreakBot that says only Hexadecimal ECID, and 1conan saved n61ap instead of n71map, now I have 9 completely useless SHSH2 files

Can you do something with SHSH2 saved with Decimal ECID?
If not, thanks anyway..

**Comment by brymonster** [comment]
thank you @tihmstar for the update. 
unfortunatley im getting the same error as @GeekBreak errorcode=-45. 
and im using HEX ECID. [Look.](https://github.com/tihmstar/futurerestore/files/874182/error.-45.txt)

my previous attempts at `checking APTicket to be valid for this restore...` gave no errors, u can see at my first post.
i have a feeling its futturerestore, not us.

**Comment by tihmstar** [comment]
Closing this since original issue is resolved.
I've explained the reason for this invalid ecid thing here #87
